CREATE TABLE IF NOT EXISTS "movies"(
  "id"      INTEGER PRIMARY KEY AUTOINCREMENT,
  "title"   TEXT NOT NULL,
  "genre"   TEXT NOT NULL,
  "year"    INT NOT NULL,
  "watched" BOOLEAN DEFAULT FALSE
);

